/**
 * Bundled skill automatic routing rule generation (2026-05-09)
 *
 * Observed in practice: when bundled SKILL.md is loaded, SkillStore writes a row, but the routing_rules table
 * is not touched. Result: the first time a user triggers keywords, routing-inject hits 0 matches, LLM sees
 * the "skill index" as just a name + description, **without routing guidance won't proactively use_skill**.
 *
 * Fix: when bundled / locally-written skill is loaded, automatically write one confidence='tentative' routing rule
 * based on the SKILL.md frontmatter's `when_to_use:` text:
 *   task_signature: 'auto:bundled:<skill-name>' (namespace isolation)
 *   trigger_condition: skill.whenToUse (LLM-readable semantics)
 *   prefer_skill: skill.name
 *   context_keywords: skill.triggerKeywords
 *   carveout: fixed text "...see the skill's own When NOT to Use section for specific boundaries"
 *   evidence: 'auto-generated from bundled SKILL.md at <ISO>'
 *
 * Does not conflict with reflection.ts path (491-501):
 *   - reflection's task_signature is chosen by LLM (e.g. 'pdf-to-word')
 *   - This path's prefix 'auto:bundled:' guarantees no collision with task_signature
 *
 * Scenarios where no rule is written:
 *   - skill.whenToUse is empty (no scenario description, routing rule has no value)
 *   - skill.kind === 'negative' (anti-patterns should not be recommended as prefer_skill)
 *   - skill.source 'self:reflect-*' (reflection-generated, uses its own routing write path)
 *   - skill.source 'self:doc-to-skill:*' (doc-to-skill learned draft skill,
 *     unverified and should not be proactively recommended; wait for reflection to validate and promote)
 *
 * Handling when the same task_signature already exists:
 *   - Already retired → do not revive (user/failure intentionally demoted it)
 *   - Active rule already exists → no-op (v1 simplified; if SKILL.md's
 *     when_to_use changed, clear 'auto:bundled:*' to let it regenerate)
 */

import type { RoutingRuleStore, RoutingRule } from './routing_rules.js';
import { extractKeywords } from './routing_rules.js';
import type { ImportableSkill } from './skillImport.js';

const AUTO_PREFIX = 'auto:bundled:';

/** Fixed carveout text for routing rules generated by this path. */
const AUTO_CARVEOUT =
  'This rule was auto-generated from bundled SKILL.md frontmatter. For specific usage boundaries / counter-examples / Anti-patterns, ' +
  'see the skill\'s own "When NOT to Use" / "Anti-patterns" sections. This rule is only a trigger guide; ' +
  'it does not replace the detailed judgment within the skill itself.';

/**
 * Determine whether a skill qualifies for "auto-write routing rule".
 * Exported for reuse by skillImport / tests.
 */
export function shouldAutoRouteSkill(skill: ImportableSkill): boolean {
  if (!skill.whenToUse || !skill.whenToUse.trim()) return false;
  if (skill.kind === 'negative') return false;
  // reflection-generated / doc-to-skill learned do not use this path
  if (skill.source && skill.source.startsWith('self:')) return false;
  return true;
}

/**
 * After a skill is loaded (created / updated), ensure the 'auto:bundled:<name>' routing
 * rule exists (if qualified).
 *
 * Returns: newly created RoutingRule if created; null if skipped / already exists / no-op.
 *
 * Failures throw; caller (skillImport) catches with try/catch so it doesn't pollute the import main flow.
 */
export function ensureBundledRoutingRule(
  rules: RoutingRuleStore,
  skill: ImportableSkill,
  now: number = Date.now(),
): RoutingRule | null {
  if (!shouldAutoRouteSkill(skill)) return null;

  const taskSignature = `${AUTO_PREFIX}${skill.name}`;
  const existing = rules.listBySignature(taskSignature);

  // Any existing state (including retired) → no-op. retired was intentionally demoted by user/failure,
  // cannot be revived just because SKILL.md was re-parsed. Other active states simplified to no-op in v1.
  if (existing.length > 0) return null;

  const triggerCondition = (skill.whenToUse ?? '').trim();

  // Key: routing-inject's keywordOverlap is a set comparison, sensitive to granularity.
  // User-side keywords go through extractKeywords (token granularity); rule.contextKeywords
  // must also be at token granularity to match.
  //
  // SKILL.md's extracted triggerKeywords are full list items (narrative, dozens of chars each),
  // storing them directly into contextKeywords causes set comparisons to never overlap → match never hits.
  //
  // Fix: extract tokens from triggerKeywords + whenToUse + description using extractKeywords,
  // merge and dedup, consistent with user-side granularity.
  const tokenSet = new Set<string>();
  for (const text of [
    triggerCondition,
    skill.description ?? '',
    ...(skill.triggerKeywords ?? []),
  ]) {
    if (!text) continue;
    for (const tok of extractKeywords(text)) {
      tokenSet.add(tok);
    }
  }
  const contextKeywords = Array.from(tokenSet);

  return rules.createRule({
    taskSignature,
    triggerCondition,
    preferSkill: skill.name,
    avoidSkills: [],
    carveout: AUTO_CARVEOUT,
    evidence: `auto-generated from bundled SKILL.md at ${new Date(now).toISOString()}`,
    confidence: 'tentative',
    contextKeywords,
    reflectionId: null,
  });
}

/** Expose constant for tests / debugging. */
export const AUTO_BUNDLED_PREFIX = AUTO_PREFIX;
